### ISSUE TITLE
An unhandled exception occurred in the plugin

### ISSUE THREAD

**Issue by dpennell** [zio/zio-intellij#318] opened 2021-08-20 18:43 UTC
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
com.intellij.openapi.util.InvalidDataException: Test configuration kind 'All in package' is not supported.
	at zio.intellij.testsupport.ZTestRunConfiguration.fromTestConfiguration(ZTestRunConfiguration.scala:44)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runnerInfo$2(ZTestRunConfiguration.scala:52)
	at scala.Option.getOrElse(Option.scala:201)
	at zio.intellij.testsupport.ZTestRunConfiguration.zio$intellij$testsupport$ZTestRunConfiguration$$runnerInfo(ZTestRunConfiguration.scala:52)
	at zio.intellij.testsupport.ZTestRunConfiguration$ZioTestCommandLineState.<init>(ZTestRunConfiguration.scala:82)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runStateProvider$1(ZTestRunConfiguration.scala:59)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration.getState(AbstractTestRunConfiguration.scala:190)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:223)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:98)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:736)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$executeConfiguration(ExecutionManagerImpl.kt:70)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:672)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:70)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:577)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
### Additional information:
<details>

ZIO plugin version: 2021.2.11.1
Scala plugin version: 2021.2.15
ZIO version(s): 1.0.9, 1.0.5
Scala version(s): 2.13.6, 2.13.6
sbt version: 1.5.1
IntelliJ version: IntelliJ IDEA 2021.2
Build #IU-212.4746.92
Java version: 11.0.11+9-b1504.13
Operating System: x86_64 Mac OS X (11.4, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment] 2021-08-22 15:21
Thanks for the report! Unfortunately this feature (run all tests in package) is not supported yet. I'll try adding it in the future...

Duplicate of #293, #26

**Closed as completed by hmemcpy** 2021-08-22 15:21 UTC
